[package]
name = "plotters-druid"
version = "0.1.0"
authors = ["mobile-bungalow <pwmay@ucsc.edu>"]
edition = "2018"

[dependencies]
druid = "0.7.0"
plotters-backend = "0.3.0"

[dev-dependencies]
plotters = "*"
rand = "*"
rand_distr = "*"
rand_xorshift = "*"
